# <div align="center">CP322-A Mini-Project 2: Machine Learning</div>
## <div align="center">Group 6</div>
### <div align="center">due on 12-Nov-2023 at 11:30 PM</div>

Imports:

In [35]:
import numpy as np
import gzip

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression


# pip install -U scikit-learn

## Datasets

### Dataset 1 (20 Newsgroup): 

Use the default train subset (subset=‘train’, and remove=([‘headers’, ‘footers’, ‘quotes’]) in  sklearn.datasets) to train the models and report the final performance on the test subset.  note: you need to start with the text data and convert the text to feature vectors. Please refer to https://scikitlearn.org/stable/tutorial/text_analytics/working_with_text_data.html for a tutorial on the steps needed for this.

In [18]:
categories = ['alt.atheism', 'soc.religion.christian',
              'comp.graphics', 'sci.med']

twenty_train = fetch_20newsgroups(subset='train',
    categories=categories, shuffle=True, random_state=42)

X = twenty_train.data
Y = twenty_train.target

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(X)

from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

In [19]:
print(twenty_train.target_names)
print(len(twenty_train.data))
print(len(twenty_train.filenames))
# print(X[0])
print("\n".join(twenty_train.data[0].split("\n")[:3]))

print(twenty_train.target_names[twenty_train.target[0]])
print(twenty_train.target[:10])
for t in twenty_train.target[:10]:
    print(twenty_train.target_names[t])

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']
2257
2257
From: sd345@city.ac.uk (Michael Collier)
Subject: Converting images to HP LaserJet III?
Nntp-Posting-Host: hampton
comp.graphics
[1 1 3 3 3 3 3 2 2 2]
comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med


  (0, 177)	0.15075567228888181
  (0, 230)	0.07537783614444091
  (0, 587)	0.07537783614444091
  (0, 2326)	0.15075567228888181
  (0, 3062)	0.07537783614444091
  (0, 3166)	0.07537783614444091
  (0, 4017)	0.15075567228888181
  (0, 4378)	0.07537783614444091
  (0, 4808)	0.07537783614444091
  (0, 5195)	0.07537783614444091
  (0, 5201)	0.07537783614444091
  (0, 5285)	0.07537783614444091
  (0, 8696)	0.30151134457776363
  (0, 9031)	0.22613350843332272
  (0, 9338)	0.07537783614444091
  (0, 9801)	0.07537783614444091
  (0, 9805)	0.15075567228888181
  (0, 9932)	0.07537783614444091
  (0, 12014)	0.07537783614444091
  (0, 12051)	0.07537783614444091
  (0, 12541)	0.07537783614444091
  (0, 12833)	0.15075567228888181
  (0, 14085)	0.07537783614444091
  (0, 14281)	0.15075567228888181
  (0, 14676)	0.07537783614444091
  :	:
  (2256, 24052)	0.07216878364870323
  (2256, 25560)	0.07216878364870323
  (2256, 26254)	0.07216878364870323
  (2256, 26998)	0.07216878364870323
  (2256, 27031)	0.14433756729740646
  (2256, 2

(2257, 35788)

In [20]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts.shape

(2257, 35788)

### Dataset 2 (IMDB Reviews):

In [27]:
import numpy as np

def read_imdb():
    print("Begin reading files.")
    directory = 'data/train/neg'
    data = []
    labels = []
    file = ''
    try:
        for filename in os.listdir(directory):
            f = open(os.path.join(directory, filename), encoding="utf-8")
            file = filename, "neg"
            for i in f:
                test = True
                while test:
                    test = False
                    k = i.find('<br /><br />')
                    if k != -1:
                        i = i[:k] + ' ' + i[k+12:]
                        test = True
                    
                data.append(i)
                labels.append(0)
                
        print("Done reading negative values.")
        
        directory = 'data/train/pos'
        
        for filename in os.listdir(directory):
            print(filename)
            f = open(os.path.join(directory, filename), encoding="utf-8")
            file = filename, "pos"
            for i in f:
             
                test = True
                while test:
                    test = False
                    k = i.find('<br /><br />')
                    if k != -1:
                        i = i[:k] + ' ' + i[k+12:]
                        test = True
                     
                data.append(i)
                labels.append(1)
                
    except Exception as e: 
        print(e)
        print("Error found in file:", file)
        
    print("Done reading positive values.")
    npdata = np.array(data)
    nplabels = np.array(labels)
    
    return npdata, nplabels
  
data, labels = read_imdb()
print("File reading complete.")
print(data)

Begin reading files.
name 'os' is not defined
Error found in file: 
Done reading positive values.
File reading complete.
[]


## Models

### Logistic Regression

In [15]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import StratifiedKFold


# Fetch the 20 newsgroups dataset
# newsgroups = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))

# Partiall dataset
# categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']


# Fetch the "train" subset of the data to be used
# newsgroups = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))
newsgroups = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))

# Vectorizing the text from the given dataset using TF-IDF to get the matrix
data_vectorizer = TfidfVectorizer(max_features=10000)
X_tfidf = data_vectorizer.fit_transform(newsgroups["data"])

# Defining the k-fold cross-validation with 5 folds measures to obtain the 5 groups
kFold = StratifiedKFold(n_splits=5,shuffle=True, random_state=42)

# Defining logistic regression model with 1000 interations
logistic_regression = LogisticRegression(max_iter=1000)

print(newsgroups["target_names"])
print(len(newsgroups["target"]))
print(len(newsgroups["data"]))


['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
11314
11314


### Decision Trees

In [33]:
from sklearn import tree
#borrow newsgroups from above cell

newsgroups_test = fetch_20newsgroups(subset="test", remove=("headers", "footers", "quotes"))
test_tfidf = data_vectorizer.fit_transform(newsgroups_test["data"])

decision_tree_classifier = tree.DecisionTreeClassifier(criterion="gini", splitter="best") #other params that can be changed but defaults should be okay otherwise

decision_tree_classifier.fit(X_tfidf, newsgroups["target"]) #train

#test
tree_results = decision_tree_classifier.predict(test_tfidf)

correct_classification_count = 0
incorrect_classification_count = 0
correct_classifications = newsgroups_test["target"]

for i in range( len(tree_results) ):

    if  tree_results[i] == correct_classifications[i]:
        correct_classification_count += 1

    else:
        incorrect_classification_count += 1

print(f"Correctly classified data points: {correct_classification_count}")
print(f"Incorrectly classified data points: {incorrect_classification_count}")

print(correct_classifications)
print(tree_results)

print(f"Mean accuracy score of decision tree: {decision_tree_classifier.score(test_tfidf, correct_classifications)}")


Correctly classified data points: 403
Incorrectly classified data points: 7129
[ 7  5  0 ...  9  6 15]
[ 2 12  7 ... 12  9  7]
Mean accuracy score of decision tree: 0.05350504514073287


### Support Vector Machines

In [ ]:
from sklearn.svm import LinearSVC


svm_model = LinearSVC()

### Ada Boost

### Random Forest

##### Dataset 1 (20 Newsgroup):

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, Y, test_size=0.2, random_state=42)

# Initialize the RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf_classifier.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the performance of the classifier
rf_accuracy = metrics.accuracy_score(y_test, y_pred)
rf_precision = metrics.precision_score(y_test, y_pred, average='weighted')
rf_recall = metrics.recall_score(y_test, y_pred, average='weighted')
rf_f1_score = metrics.f1_score(y_test, y_pred, average='weighted')

print(f"Accuracy: {rf_accuracy:.4f}")
print(f"Precision: {rf_precision:.4f}")
print(f"Recall: {rf_recall:.4f}")
print(f"F1 Score: {rf_f1_score:.4f}")


Accuracy: 0.8606
Precision: 0.8803
Recall: 0.8606
F1 Score: 0.8618


##### Dataset 2 (IMDB Reviews):

## Validation

In [36]:
from sklearn.model_selection import cross_val_score, KFold
import pandas as pd

# Define models with their hyperparameters
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'AdaBoost': AdaBoostClassifier(n_estimators=50, random_state=42),
    'SVM': SVC(kernel='linear', probability=True, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42)
}

# Initialize KFold cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Create a DataFrame to store performance metrics
results_df = pd.DataFrame(columns=['Model', 'Accuracy', 'Precision', 'Recall', 'F1 Score'])

# Model validation pipeline
for model_name, model in models.items():
    accuracy_scores = cross_val_score(model, X_tfidf, Y, cv=kf, scoring='accuracy')
    precision_scores = cross_val_score(model, X_tfidf, Y, cv=kf, scoring='precision_weighted')
    recall_scores = cross_val_score(model, X_tfidf, Y, cv=kf, scoring='recall_weighted')
    f1_scores = cross_val_score(model, X_tfidf, Y, cv=kf, scoring='f1_weighted')

    results_df = results_df.append({
        'Model': model_name,
        'Accuracy': accuracy_scores.mean(),
        'Precision': precision_scores.mean(),
        'Recall': recall_scores.mean(),
        'F1 Score': f1_scores.mean()
    }, ignore_index=True)

# Print the results table
print(results_df)

# Identify the best model for each metric
best_accuracy_model = results_df.loc[results_df['Accuracy'].idxmax()]['Model']
best_precision_model = results_df.loc[results_df['Precision'].idxmax()]['Model']
best_recall_model = results_df.loc[results_df['Recall'].idxmax()]['Model']
best_f1_model = results_df.loc[results_df['F1 Score'].idxmax()]['Model']

print("\nBest Models:")
print(f"Accuracy: {best_accuracy_model}")
print(f"Precision: {best_precision_model}")
print(f"Recall: {best_recall_model}")
print(f"F1 Score: {best_f1_model}")


C:\Users\twbm\AppData\Local\Temp\ipykernel_11924\1104062206.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append({
C:\Users\twbm\AppData\Local\Temp\ipykernel_11924\1104062206.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append({
C:\Users\twbm\AppData\Local\Temp\ipykernel_11924\1104062206.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append({
C:\Users\twbm\AppData\Local\Temp\ipykernel_11924\1104062206.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append({


                 Model  Accuracy  Precision    Recall  F1 Score
0        Random Forest  0.880811   0.895755  0.880811  0.881001
1             AdaBoost  0.739916   0.755450  0.739916  0.740215
2                  SVM  0.963663   0.964693  0.963663  0.963687
3        Decision Tree  0.780245   0.781392  0.780245  0.780037
4  Logistic Regression  0.945496   0.948900  0.945496  0.945737

Best Models:
Accuracy: SVM
Precision: SVM
Recall: SVM
F1 Score: SVM


C:\Users\twbm\AppData\Local\Temp\ipykernel_11924\1104062206.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append({
